### ISSUE TITLE
[feature request] $redirect as global?

### ISSUE THREAD

**Issue by trenc** [textpattern/com_connect#46]
Hi Stef,
it's an issue do declare the $redirect variable as global, so we can modify it in a callback hook?

**Comment by Bloke** [comment]
I'd rather not introduce more globals: the plugin is littered with them already. But I can see the benefit in being able to modify the redirect value from the `zem_contact.deliver` callback in case you want to return from it but not perform the redirect. Is there a neat way you can see of passing it in? I'd like to limit the number of parameters too: it already has 6!

The only way I can think of is to relabel the `$flags` param as something else (like, uhhh, `behaviour`) and use it to pass both the `isCopy` and the `redirect` string into the function. I can then bundle up the redirect as part of the `$payload` passed to the callback?

Would that work for you or can you think of something better?

**Comment by trenc** [comment]
Another little thingy, I've seen while testing: `$thing` in 'zem_contact_option' should be parsed by `parse()`.
