### ISSUE TITLE
Composer install

### ISSUE THREAD

**Issue by philwareham** [textpattern/com_connect#50]
It would be nice to have a [composer.json file](https://getcomposer.org/doc/01-basic-usage.md#composer-json-project-setup) and register the plugin with [Packagist](https://packagist.org).

Also IMHO the name 'zem_contact_reborn'... really? This means nothing and the plugin is so far from the original version a new, more sensible, name would be better - along with a proper semver version number. Just credit zem (and all other contributors) somewhere in the README and code.

**Comment by Bloke** [comment]
Composer and Packagist are currently outside my field of expertise, but I have an account on the latter so presumably it's not hard to add the project to Packagist.

As for the plugin name, it's only really for compatibility with existing tags. Come up with something cool and I'll consider using it. Although it still can be used as a contact form plugin, it's now a lot more capable -- more like a customer contact platform -- so I suppose it makes sense to rebrand. Negatives:

* Pain for users to convert their current contact tags.
* Plugins that use the callbacks would all need to change.
* The new plugin modules I've introduced with 'zcr_' prefix that hook into the callbacks would have to be rebranded also.
* Documentation alterations (maybe only a search and replace job, but might have a few other parts to fix up).

Can you rename GitHub projects, btw?

**Comment by philwareham** [comment]
A far as I know, all you need to do is add a composer.json file with minimum of:

~~~~
{
  "name": "your-vendor-name/package-name",
  "description": "A short description of what your package does",
  "type": "textpattern-plugin",
  "require": {
    "php": ">=5.3.6",
    "textpattern/lock": ">=4.6.0",
    "textpattern/installer": "*"
    }
}
~~~~

And [follow the recommendations here](https://github.com/gocom/textpattern-installer#quick-start-for-developers). Change the php and texpattern version to whatever the minimum is. Register the package at Packagist, release a new version with tag on GitHub. Jukka has already written a Composer autoloader for use with Textpattern so that should be it.

As for the name, it would be wise to agree on something before registering on Packagist. Something like `pub_html_form` v1.0.0 I guess. Can old tag names be kept along with new ones?

You can rename GitHub projects and old URLs are automatically redirected.

**Comment by philwareham** [comment]
Done and tested. Works fine. Closing.
