### ISSUE TITLE
Labels are printed twice (4.7.0dev)

### ISSUE THREAD

**Issue by philwareham** [textpattern/com_connect#53]
With the latest beta of the plugin and running recent Textpattern 4.7.0dev I'm getting duplicated labels for any tags that contain the `label=""` attribute, see screen grab.

![form-grab](https://cloud.githubusercontent.com/assets/413665/25428890/23d383b2-2a6f-11e7-94b5-1519ee83d112.png)

**Comment by Bloke** [comment]
That's an issue with the global `label` attribute adding its own label as well as the plugin doing it.

The plugin uses its own attribute parser, which conflicts with the core one. There's a temporary fix that Oleg outlined. Add this line:

```
    lAtts(array('label' => ''), $atts, false);
```

to the top of the `zem_contact_lAtts()` function. But I think it has other unintended side effects (see #51 and #52 I posted yesterday). I need to verify those and work out if this fix is long-term useful, or if I need to find another way round it.

**Comment by bloatware** [comment]
Sorry for the trouble, if it comes from global attributes. In place of the `lAtts()` call above, you can try
```
global $txp_atts;
$txp_atts = null;
```
This should unset all global processing, at least for tags that use `zem_contact_lAtts()`. But the issue may be more complicated if ZCR does not systematically pass by the usual `processTags()` calls. I had no time yet to look into its code, sorry, so take it for what it's worth.
