### ISSUE TITLE
Label not being suppressed with label="" on txp 4.80dev

### ISSUE THREAD

**Issue by jools-r** [textpattern/com_connect#67]
With the current 4.80dev version, I get an empty label when I use `label="" name="my-form-field"` to suppress its display but keep the form name.

Interestingly, adding the attribute `label_position=""` works to suppress it entirely.

BTW: my main motivation for suppressing the label field is the ability to give it a different class to the field. A `labelclass` / `label_class` attribute might be useful here…

**Comment by Bloke** [comment]
I'll test this. Likely to be the way we're using 'label' vs the way it's handled as a global attribute now. I'll see if stripping out handling such globals directly in the plugin might work.
