### ISSUE TITLE
Some aria attributes needed

### ISSUE THREAD

**Issue by cara-tm** [textpattern/com_connect#72]
Could you please add some `aria` attributes for the checkbox tag?
For Ay11 accessibility purpose these attributes are required (while their values will be managed in javascript depending on states):

    function com_connect_checkbox($atts)
    {
    global $com_connect_error, $com_connect_submit, $com_connect_flags;

    extract(com_connect_lAtts(array(
        'aria_checked'   => '',
        'aria_invalid'   => '',
        ...

**Comment by philwareham** [comment]
Checkboxes don't need ARIA if they are actually checkboxes - since the browser announces them to screen readers properly. You'd only need the ARIA attributes if you were changing the default behaviour of other elements to make faux-checkboxes. e.g. `<span role="checkbox" aria-checked="true">`.
