### ISSUE TITLE
help file: spurious literal `br` after attributes

### ISSUE THREAD

**Issue by phiw13** [textpattern/com_connect#73]
Open the Help file -> Tags.
For any given tags list, look at the attributes:
Pattern: `attribute-name="value"<br />explanation`

Expected: render a line-break or nothing.

The text on the GitHub page displays the linebreak correctly. I suppose there is a disconnect somewhere between the server used Markdown and the Textpattern used Textile.

(version 4.7.0) 

<img width="276" alt="comconnect-help" src="https://user-images.githubusercontent.com/8944809/124882291-30a03580-e00b-11eb-8c50-2e1af0d13310.png">

**Comment by phiw13** [comment]
Lovely, thanks.
Now 189% more readable :-)

**Comment by Bloke** [comment]
Of course, this does mean that the readme on GitHub is rubbish since it doesn't support definition lists, but I'd rather it be right in the docs than here.
