### ISSUE TITLE
Inserting the output of a com_connect_select in in the subject line of a mail message fails

### ISSUE THREAD

**Issue by phiw13** [textpattern/com_connect#75]
forum thread: https://forum.textpattern.com/viewtopic.php?pid=331182#p331182

Textpattern 4.8.7 / PHP 8.0.2, latest plugin version (4.7.0+)

The key is trying to fetch and then outputting the result of a `<com_connect_select />` via some `<txp:php />` snippet (doesn't matter constructing the subject line of the or inserting it inside the body of a mail message).

```
<pre dir="auto">Tag error: <b><txp:php>     global $com_connect_form;     echo 'Contact [sitename] - ' . $com_connect_form['Subject']; </txp:php></b> -> <b> Warning: Array to string conversion while parsing form <strong>contact-subject</strong> on page <strong>default</strong></b></pre>
Contact [sitename] - Array
```

Probable consequence of this: https://github.com/textpattern/com_connect/commit/3cf17cadc78cb93824f026d5abe962e61f4e3a34

(but don’t trust my failing memory too much!)

**Comment by Bloke** [comment]
I think your analysis is probably right. I'll run some tests when I get a moment and see what's going on. Thanks for the report.

**Comment by Bloke** [comment]
Documentation needed updating. Fixed.

**Comment by phiw13** [comment]
Yes, works fine now. TY.
