### ISSUE TITLE
Passing null to parameter #1 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by phiw13** [textpattern/com_connect#78]
TXP 4.8.8 latest-GH build / debuggin enabled
PHP 8.1.0 (localhost/ homebrew build)

STR: Create com connect form, view the public side:

```
Tag error: txp:com_connect_text break="" class="" label="Name" name="name" placeholder="Your Name" /> ->  8192: strtr(): Passing null to parameter #1 ($string) of type string is deprecated while parsing form lcn_contact_main on page default
textpattern/lib/txplib_misc.php:39 strtr()
deNull()
textpattern/lib/txplib_misc.php:70 array_map()
textpattern/lib/txplib_misc.php:39 doArray()
plugin_core/com_connect/com_connect.php:1452 deNull()
plugin_core/com_connect/com_connect.php:397 com_connect_lAtts()
com_connect_text()
textpattern/vendors/Textpattern/Tag/Registry.php:140 call_user_func()
textpattern/lib/txplib_publish.php:559 Textpattern\Tag\Registry->process()
textpattern/lib/txplib_publish.php:409 processTags()
```

Repeat for every com_connect tag inserted.

The form submits apparently, I have currently no idea what the payload looks like. localhost is not configured for that. In “live” mode, no errors are displayed.

**Comment by phiw13** [comment]
Hmm, did this: https://github.com/textpattern/textpattern/commit/c9cc5ae2a4e2bcdb3d82ca3e26edd7a11a06f2ce eventually improve the situation? On a form with 10 fields (text / select (1)/ textarea (1) I am down to just one error: `Tag error: <txp:com_connect_submit label="Submit" />`. Previously it screamed for every `com_connect` tag.

**Comment by Bloke** [comment]
Yes, core was the main issue.

So now you get the same error as in the OP, but only on the com_connect_submit tag? If so, maybe that handles things differently and doesn't go through `lAtts()` for some reason. I'll have to check.

**Comment by phiw13** [comment]
Yeas that is it: only `com_connect_submit` has an issue.

And of course still no idea what the payload –what is actually being sent– looks like. I cannot currently test that. The form tells me that the message has been sent (my success/thank you page).

**Comment by phiw13** [comment]
> still no idea what the payload […]

Now test on  a live server. One error on `<txp:com_connect_submit label="Submit" />` as flagged above. No error when processing and sending the form. Payload is complete.

Tested with a very basic contact form.

**Comment by Bloke** [comment]
I cannot reproduce this. There's got to be something specific to either the version of PHP you're using compared to mine, or something in your form that's different. I can't get the com_connect_submit tag to throw this warning.

Can you please supply the contact form you're using so I can try to track this down? Thanks.

Note, btw that there have been some updated recently so please grab the latest version and retest.

**Comment by phiw13** [comment]
PHP 8.1.1 (live server) and 8.1.2 (localhost), Textpattern 4.8.8 release. I use the `pap_comconnect` spam trap plugin, same issue when disabled.

This is the form:

```
<txp:com_connect class="contact-form-form" classes="element:warn-field, required:required-field, thanks:thanks-message, wrapper:error-message" label="" to="me@example.com" from="me@example.com" subject="Contact us" body_form="pw_contact_message_body" thanks_form="pw_contact_thanks">
<div class="input-field"><txp:com_connect_email break="" class="" label="Email" name="email" placeholder="Your email address" /></div>
<div class="input-field"><txp:com_connect_text break="" class="" label="Name" name="name" placeholder="Your Name" /></div>
<div class="input-field contact-subject">
  <txp:com_connect_select break="" class="" label="Subject" name="subject">
    <txp:com_connect_option class="" label="{Select one}" selected />
    <txp:com_connect_option class="" label="General enquiry" />
    <txp:com_connect_option class="" label="Site issue" />
    <txp:com_connect_option class="" label="Other…" />
  </txp:com_connect_select>
</div>
<div class="contact-message"><txp:com_connect_textarea class=""  name="message" break="" label="Message" /></div>
<p><small>Please note that fields marked with <span class="required">*</span> are required</small></p>
<txp:com_connect_serverinfo name="REMOTE_ADDR" label="IP number" />
<div class="submitfield"><txp:com_connect_submit label="Submit" /></div>
</txp:com_connect>
```

i tried replace the `txp:com_connect_select ` container with one using the `options` attribute; that gives the same result.

Contact form is here: `https://emps.l-c-n.com/contact/` – with debugging on.

**Comment by Bloke** [comment]
Ahaaaaa, thank you. It's throwing a slightly different error message to the one in the OP. That's why I couldn't figure it out. This one's complaining about `strlen()` not `strtr()`. That must be because there's no container content. I'll try and patch that.

**Comment by Bloke** [comment]
Give that a whirl please.

**Comment by phiw13** [comment]
Yes sir no more beautiful debug message(s). Form sends correctly and arrives promptly with nothing missing.

I’ll test that other issue tomorrow or so.
