### ISSUE TITLE
HTML5-conform self-closing (void) tags

### ISSUE THREAD

**Issue by jools-r** [textpattern/com_connect#84]
The W3C validator complains about `/>` endings of self-closing (void) tags when using an HTML5 doctype.

I tracked down where these occur in the plugin code and made a [small commit](https://github.com/jools-r/com_connect/commit/48c7a7172c32b00f94a41b146abad80c4b1b1af5) in a branch of my own fork that switches these to plain `>`-tag endings when the doctype setting is set to HTML5. In combination with a similar [commit in the textpattern code](https://github.com/textpattern/textpattern/issues/1836) it appears to appease the W3C validator.

Is this worth submitting as a PR?

**Comment by Bloke** [comment]
Ooh yes please. Fire away.

**Comment by jools-r** [comment]
PR #85 submitted :-)

**Comment by jools-r** [comment]
Thanks!
