### ISSUE TITLE
Bug: Multiple "to" recipients produces invalid_argument: address error using SMTPmail

### ISSUE THREAD

**Issue by jools-r** [textpattern/com_connect#89]
Using the current 4.9.0 dev version of com_connect and 4.9 dev of Textpattern:

Specify more than one email address in the `to` attribute, separated by commas, while sending using "enhanced" SMTP email.

The contact form returns `invalid_argument: address` and does not send. Using just one email address sends successfully.

This error seems to be being produced by the `addAddress` function of [/Textpattern/Mail/Adapter/SMTPMail.php](https://github.com/textpattern/textpattern/blob/55ceb545ee0ec37131e63eb18655716d95d321f3/textpattern/vendors/Textpattern/Mail/Adapter/SMTPMail.php#L351). A `var_dump` of the incoming variables of the addAddress function shows that `to` string includes both email addresses with a comma, which I guess fails the email validation and throws the error.

Presumably the send mechanism (for PHPmailer) needs to determine if `$to` is a list and if so loop over the list and call the function multiple times.

**Comment by Bloke** [comment]
Ooft, good catch, thank you. I'll debug this. Probably a faulty assumption on my part that passing multiple adresses to PHPMailer would figure out that they're a list.

**Comment by Bloke** [comment]
Yeah, that'll need fixing, thanks. I'll just make an array out of them and validate each one.

From all the resources I've found so far, dating from last year back to ten years ago, `addAddress()` (and presumably by extension `addCC()`, `addBCC()` etc) only take one email per call.

**Comment by Bloke** [comment]
Hmmm, annoying. For both `Mail` and `SMTPMail` classes, this can either be patched in the `addAddress()` functions - effectively allowing an array of addresses to be passed, or to split them at comma. Or it can be done in the magic `__call()` method, which handles any field setting that does not explicitly have its own setter.

Do we need to be careful not to permit invalid things such as multiple `->from()` addresses? It seems that multiple replyTo addresses are supported, but I've never thought about that. The function is called `addReplyTo()` which implies more than one can be specified, whereas from addresses use `setFrom()`.

I suppose if more than one From address is specified then only the last will be used, so maybe we can just ignore this and treat every field as a potential string or array, which simplifies matters.

**Comment by jools-r** [comment]
I don't feel qualified to say which is the best way but I can't imagine any sensible case for multiple from addresses.

The name <-> email correspondence is in PHPmailer, right? I can't see where we can currently specify names in com_connect. But [the simple example at PHPmailer](https://github.com/PHPMailer/PHPMailer#a-simple-example) suggests the name is optional. 

I admit I hadn't thought it through in the same level of detail / re-usability. My initial thought was that if the `to` attribute is the only one that supports multiple addresses, one only need detect if `$to` is a list, and if so loop over an array of the list, calling addAddress several times over. Presumably that would just chains more addAddress instances as shown in [the simple example](https://github.com/PHPMailer/PHPMailer#a-simple-example). Our class in the vendors folder supports more options than com_connect currently supports, e.g. CC and BCC.

**Comment by Bloke** [comment]
Yeah, com_connect doesn't support those additional fields out of the box, but our mail engine will need to.

I think https://github.com/textpattern/textpattern/commit/15c8be37fc06e7fcd2be8a5b61c3cb8898b6b3f7 nails it, but please test with both com_connect and PHP via internal mail and enhanced PHPMailer, e.g.:

``` php
<txp:php>
$message = Txp::get('\Textpattern\Mail\Compose')->getDefaultAdapter();
$message->from('somebody@example.com')
    ->to('first@example.com, second@example.com, third@example.com, fourth@example.com', 'First person, , Third person')
    ->subject('Test multiple recipients')
    ->body('This is a test. Nothing to see here, move along.');
$message->send();
</txp:php>
```
Note the absence of the second and fourth names, which tests if it correctly skips over the optional names and they still match the email addresses correctly.

**Comment by jools-r** [comment]
I've tested it now on a 4.9.0 dev installation with regular (non-enhanced) email and it behaves exactly as above. 👍

My email client gives me the option to reply to reply to all. All then appear in the To: or CC fields as the email arrived.

I reckon this can be closed now.
